### ISSUE TITLE
simpleeval + sqlalchemy query

### ISSUE THREAD

**Issue by icarmi** [danthedeckie/simpleeval#48]
Hi,

I'm trying to get the safety of simpleeval to work with sqlalchemy's core query:
Something like:

```
tbl = Table('mytable', meta)
names = tbl.c._data
myexpr = 'mycol > 5'
se = simpleeval.EvalWithCompoundTypes(names=names)
safe_filter = se.eval(myexpr)  # <-- I get an error
results = session.query(tbl).filter(safe_filter)
```
I'm getting this error on eval():

> TypeError: Boolean value of this clause is not defined

For the record, this does work:
```
tbl = Table('mytable', meta)
names = tbl.c._data
myexpr = 'mycol > 5'
unsafe_filter = eval(myexpr, names)
results = session.query(tbl).filter(unsafe_filter)
```
It looks like eval() is returning: sqlalchemy.sql.elements.BinaryExpression, which breaks simpleeval...

Any hope of getting this to work? Am I doing something wrong?

Thanks!

**Comment by danthedeckie** [comment]
Interesting!  I'll investigate that.

Are you sure that it's the `se.eval` thats throwing the error, not something in `filter`?

Could you post the whole traceback?

I can see a potential issue where simpleeval might return a Boolean rather than something else in the case of an object that overloads the comparison operator - but it shouldn't crash with that error, however, if it returned a Boolean, then sqlalchemy might be expecting something else in the filter function?

**Comment by icarmi** [comment]
Awesome, thank you!!

And yup, it's the se.eval() that's raising the exception:

```
>>> safe_filter = se.eval(expr)
Traceback (most recent call last):
  File "/home/ido/Software/pycharm-2018.2.3/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/home/ido/.envs/rex2/lib/python3.6/site-packages/simpleeval.py", line 283, in eval
    return self._eval(ast.parse(expr.strip()).body[0].value)
  File "/home/ido/.envs/rex2/lib/python3.6/site-packages/simpleeval.py", line 294, in _eval
    return handler(node)
  File "/home/ido/.envs/rex2/lib/python3.6/site-packages/simpleeval.py", line 338, in _eval_compare
    if self.operators[type(operation)](left, right):
  File "/home/ido/.envs/rex2/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 2993, in __bool__
    raise TypeError("Boolean value of this clause is not defined")
TypeError: Boolean value of this clause is not defined

```

Yea, I'm not exactly sure what's going on... I know that the expression does not return a _bool_, instead it returns an SQL Alchemy object (_sqlalchemy.sql.elements.BinaryExpression_) that is used later by _.query().filter(...)_

**Comment by icarmi** [comment]
Another clue, I think that typecasting to bool is what raises the exception...
From the trace:

```
File "/home/ido/.envs/rex2/lib/python3.6/site-packages/simpleeval.py", line 338, in _eval_compare
    if self.operators[type(operation)](left, right):
```

Will it work if the if checks for None instead of True?, as in:

`if self.operators[type(operation)](left, right) is not None:`

**Comment by danthedeckie** [comment]
I think this should be fixed now!

SimpleEval expected a comparison to return a boolean-able object (which seems reasonable...) except the BinaryExpression explicitly over-rides `__bool__` and raises that `TypeError`.

Python is just so (amazingly / frustratingly) dynamic, there are very few things that seem normal that cannot be over-ridden.

If this doesn't fix it, then please re-open the issue!

**Comment by icarmi** [comment]
Works!! Thanks a lot!

Yeah, I was also a bit surprised to see that they disabled the boolean type cast!!

**Comment by icarmi** [comment]
I celebrated too soon... Basically the original expression works ("mycol > 5"), but SQLAlchemy also has an ability to do something like this: "mycol.in_([5, 6, 7])", which is breaking:

```
  File "/home/ido/personalics/rexv2/libs/simpleeval/simpleeval.py", line 490, in eval
    return super(EvalWithCompoundTypes, self).eval(expr)
  File "/home/ido/personalics/rexv2/libs/simpleeval/simpleeval.py", line 290, in eval
    return self._eval(ast.parse(expr.strip()).body[0].value)
  File "/home/ido/personalics/rexv2/libs/simpleeval/simpleeval.py", line 301, in _eval
    return handler(node)
  File "/home/ido/personalics/rexv2/libs/simpleeval/simpleeval.py", line 358, in _eval_call
    func = self._eval(node.func)
  File "/home/ido/personalics/rexv2/libs/simpleeval/simpleeval.py", line 301, in _eval
    return handler(node)
  File "/home/ido/personalics/rexv2/libs/simpleeval/simpleeval.py", line 420, in _eval_attribute
    return node_evaulated[node_evaulated]
  File "/home/ido/.envs/rex2/lib/python3.6/site-packages/sqlalchemy/sql/operators.py", line 411, in __getitem__
    return self.operate(getitem, index)
  File "/home/ido/.envs/rex2/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 694, in operate
    return op(self.comparator, *other, **kwargs)
  File "/home/ido/.envs/rex2/lib/python3.6/site-packages/sqlalchemy/sql/operators.py", line 411, in __getitem__
    return self.operate(getitem, index)
  File "<string>", line 1, in <lambda>
  File "/home/ido/.envs/rex2/lib/python3.6/site-packages/sqlalchemy/sql/type_api.py", line 63, in operate
    return o[0](self.expr, op, *(other + o[1:]), **kwargs)
  File "/home/ido/.envs/rex2/lib/python3.6/site-packages/sqlalchemy/sql/default_comparator.py", line 192, in _getitem_impl
    _unsupported_impl(expr, op, other, **kw)
  File "/home/ido/.envs/rex2/lib/python3.6/site-packages/sqlalchemy/sql/default_comparator.py", line 197, in _unsupported_impl
    "this expression" % op.__name__)
NotImplementedError: Operator 'getitem' is not supported on this expression
```
I'm not sure if this is a bug or a safety feature in simpleeval... 

On a different note, I was able to add compound operators without any problems, using:
```
from sqlalchemy import or_, and_

se.operators[ast.BitAnd] = and_
se.operators[ast.BitOr] = or_

se.eval("(age > 5) & (age < 10)")  # works!
```

**Comment by icarmi** [comment]
Had a crazy week -- but the fix works!! Thanks again!!!
