### ISSUE TITLE
Failing test TestTryingToBreakOut

### ISSUE THREAD

**Issue by mbehrle** [danthedeckie/simpleeval#5]
TestTryingToBreakOut is currently failing with

```
I: pybuild base:170: python2.7 setup.py test 
running test
running egg_info
creating simpleeval.egg-info
writing simpleeval.egg-info/PKG-INFO
writing top-level names to simpleeval.egg-info/top_level.txt
writing dependency_links to simpleeval.egg-info/dependency_links.txt
writing manifest file 'simpleeval.egg-info/SOURCES.txt'
reading manifest file 'simpleeval.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'simpleeval.egg-info/SOURCES.txt'
running build_ext
test_bools_and_or (test_simpleeval.TestBasic) ... ok
test_comparisons (test_simpleeval.TestBasic) ... ok
test_default_conversions (test_simpleeval.TestBasic)
conversion between types ... ok
test_if_else (test_simpleeval.TestBasic)
x if y else z ... ok
test_maths_with_floats (test_simpleeval.TestBasic) ... ok
test_maths_with_ints (test_simpleeval.TestBasic)
simple maths expressions ... ok
test_mixed_comparisons (test_simpleeval.TestBasic) ... ok
test_load_file (test_simpleeval.TestFunctions)
add in a function which loads data from an external file. ... ok
test_randoms (test_simpleeval.TestFunctions)
test the rand() and randint() functions ... ok
test_dict (test_simpleeval.TestNames)
using a normal dict for names lookup ... ok
test_from_doc (test_simpleeval.TestNames)
the 'name first letter as value' example from the docs ... ok
test_func (test_simpleeval.TestNames)
using a function for 'names lookup' ... ok
test_none (test_simpleeval.TestNames)
what to do when names isn't defined, or is 'none' ... ok
test_import (test_simpleeval.TestTryingToBreakOut)
usual suspect. import ... ok
test_long_running (test_simpleeval.TestTryingToBreakOut)
exponent operations can take a long time. ... ok
test_python_stuff (test_simpleeval.TestTryingToBreakOut)
other various pythony things. ... ok
test_string_length (test_simpleeval.TestTryingToBreakOut) ... ERROR
test_basic_run (test_simpleeval.Test_simple_eval) ... ok
test_default_functions (test_simpleeval.Test_simple_eval) ... ok

======================================================================
ERROR: test_string_length (test_simpleeval.TestTryingToBreakOut)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/buildd/simpleeval-0.8.2/test_simpleeval.py", line 199, in test_string_length
    self.t("'" + (50000 * "stuff") + "'", 0)
  File "/tmp/buildd/simpleeval-0.8.2/test_simpleeval.py", line 24, in t
    return self.assertEqual(self.s.eval(expr), shouldbe)
  File "/tmp/buildd/simpleeval-0.8.2/simpleeval.py", line 209, in eval
    return self._eval(ast.parse(expr).body[0].value)
  File "/tmp/buildd/simpleeval-0.8.2/simpleeval.py", line 223, in _eval
    node.id, len(node.s), MAX_STRING_LENGTH))
AttributeError: 'Str' object has no attribute 'id'

----------------------------------------------------------------------
Ran 19 tests in 0.009s

FAILED (errors=1)
```

**Comment by mbehrle** [comment]
JFTR: same with Python 3.4

**Comment by danthedeckie** [comment]
Hi,
Thanks for that.  Apparently I forgot to push the latest version that's on github to pypi. Sorry!
I'm currently away, and behind a very restricted corporate firewall, so cannot push the latest version up.
As soon as I can get an unrestricted internet connection, I'll bump the version number, and push it to pypi.

Until then, I'm afraid the best solution is for you to pull down the latest version from github.

I hope that helps!

Dan

**Comment by mbehrle** [comment]
Hi,

thanks, I see. Will try with https://github.com/danthedeckie/simpleeval/commit/aaee5030d20bd832373485e2c78084f4d92227f7.

Best,
Mathias

**Comment by mbehrle** [comment]
Thanks, works! Looking forward tothe next release!
