### ISSUE TITLE
Failing test with python3.2

### ISSUE THREAD

**Issue by mbehrle** [danthedeckie/simpleeval#6]
With python3.4 no errors (s. https://github.com/danthedeckie/simpleeval/issues/5), but when building for Debian wheezy, which only has python3.2 the following error occurs:

```
I: pybuild base:170: python3.2 setup.py test
running test
running build_py
running egg_info
creating /tmp/buildd/simpleeval-0.8.2/.pybuild/pythonX.Y_3.2/build/simpleeval.egg-info
writing /tmp/buildd/simpleeval-0.8.2/.pybuild/pythonX.Y_3.2/build/simpleeval.egg-info/PKG-INFO
writing top-level names to /tmp/buildd/simpleeval-0.8.2/.pybuild/pythonX.Y_3.2/build/simpleeval.egg-info/top_level.txt
writing dependency_links to /tmp/buildd/simpleeval-0.8.2/.pybuild/pythonX.Y_3.2/build/simpleeval.egg-info/dependency_links.txt
writing manifest file '/tmp/buildd/simpleeval-0.8.2/.pybuild/pythonX.Y_3.2/build/simpleeval.egg-info/SOURCES.txt'
reading manifest file '/tmp/buildd/simpleeval-0.8.2/.pybuild/pythonX.Y_3.2/build/simpleeval.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file '/tmp/buildd/simpleeval-0.8.2/.pybuild/pythonX.Y_3.2/build/simpleeval.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 22, in <module>
    'Programming Language :: Python :: 3',
  File "/usr/lib/python3.2/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.2/distutils/dist.py", line 917, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.2/distutils/dist.py", line 936, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/test.py", line 137, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/usr/lib/python3/dist-packages/setuptools/command/test.py", line 117, in with_project_on_sys_path
    func()
  File "/usr/lib/python3/dist-packages/setuptools/command/test.py", line 146, in run_tests
    testLoader = loader_class()
  File "/usr/lib/python3.2/unittest/main.py", line 123, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python3.2/unittest/main.py", line 191, in parseArgs
    self.createTests()
  File "/usr/lib/python3.2/unittest/main.py", line 198, in createTests
    self.module)
  File "/usr/lib/python3.2/unittest/loader.py", line 137, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.2/unittest/loader.py", line 137, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.2/unittest/loader.py", line 96, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "/tmp/buildd/simpleeval-0.8.2/test_simpleeval.py", line 87
    self.t('"Test Stuff!" + str(11)', u"Test Stuff!11")
                                                     ^
SyntaxError: invalid syntax
```

**Comment by danthedeckie** [comment]
I think this is fixed now.
